# --- Этап 1: Сборка (Build) ---
# ИСПРАВЛЕНИЕ 1: Берем Node 20 (или 22), так как этого требует Vite
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- Этап 2: Раздача через Nginx ---
FROM nginx:alpine

# ИСПРАВЛЕНИЕ 2: Vite собирает проект в папку 'dist', а не 'build'
# Если вдруг у тебя Create React App, верни обратно на /app/build
COPY --from=build /app/dist /usr/share/nginx/html

# Копируем конфиг Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]