# Generated by Django 5.2.6 on 2025-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='year_level',
            field=models.CharField(choices=[('Preparatory', 'Preparatory Year'), ('Freshman', 'Freshman Year'), ('Sophomore', 'Sophomore Year'), ('Junior', 'Junior Year'), ('Senior', 'Senior Year')], default='Freshman', max_length=20),
        ),
    ]
